### ISSUE TITLE
absolute path is not working

### ISSUE THREAD

**Issue by rjnqlik** [ralfbecher/QlikSense_Extension_Image#4]
Dear Team,

for this extension, the absolute path is not working, tried using .PNG and .JPG files, please help. 

Regards,
J. Ravichandra Kumar

**Comment by saikatjana2309** [comment]
Hello, I also have the same issue, Though it is not a showstopper in the server environments, a fix would be helpful. Thanks.

**Comment by ralfbecher** [comment]
Actually, an absolute path outside the (web) server context cannot work here!
