### ISSUE TITLE
Problems with setting image path 

### ISSUE THREAD

**Issue by zellerivo** [ralfbecher/QlikSense_Extension_Image#7]
Hi Ralf, 

thank you very much for creating this extension! I use Qlik Sense Enterprise at my company. I have problems specifying a path and get the pictures from there. Is this even possible with the server version? We need a folder where pictures are updated on a weekly basis. These pictures should be accessible by the app. 

![Unbenannt](https://user-images.githubusercontent.com/27508006/65607364-b37a0c80-dfac-11e9-844e-a3d6fdef444c.PNG)

**Comment by ralfbecher** [comment]
You can use images from inside Qlik's content path only.
